[project]
name = "harvestpro"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.certification-system]
path = "contracts/certification-system.clar"
depends_on = []

[contracts.crop-tracking]
path = "contracts/crop-tracking.clar"
depends_on = []

[contracts.farmer-registry]
path = "contracts/farmer-registry.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
